### ISSUE TITLE
Trying to find the Zoneminder docker container

### ISSUE THREAD

**Issue by cdrage** [hyperbolic2346/kubernetes#1]
Hey @hyperbolic2346 awesome job on all these Kubernetes artifacts!

I'm trying to use your Zoneminder artifact file(s). But I'm unable to find the Docker containers that you use (you have it hardcoded as: `10.0.1.14:5000/zoneminder`)

Are you able to make these containers public?

**Comment by hyperbolic2346** [comment]
@cdrage I believe I still have this container, but I wouldn't recommend using mine. I set it up and tested it out and decided to go a different route. I'm using motion still for now. I have the Dockerfile [over here](https://github.com/hyperbolic2346/coreos/tree/master/dockerfiles/zoneminder), but I would only suggest using this as a starting point as I will not maintain it.
